# Generated by scripts/generate_platform_adapters.py; do not edit.
"""One RFC 9457 problem+json shape on a FastAPI app.

    from problem_fastapi import install_problem_handlers

    def create_app() -> FastAPI:
        app = FastAPI()
        install_problem_handlers(app)
        return app

The media type is the part that gets forgotten: a JSON body with the right keys served as
application/json is not problem+json, and a client cannot tell it from a success payload.
"""
from __future__ import annotations

from typing import Any

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
# The Starlette base catches FastAPI's HTTPException (a subclass) *and* the framework's own
# 404/405 for an unknown route, which a fastapi.HTTPException handler alone would miss.
from starlette.exceptions import HTTPException as StarletteHTTPException

PROBLEM_TYPE_BASE = "https://errors.example.internal"
PROBLEM_MEDIA_TYPE = "application/problem+json"

_TITLES = {
    400: "Malformed request", 401: "Unauthenticated", 403: "Forbidden", 404: "Not found",
    409: "Conflict", 422: "Validation failed", 429: "Too many requests",
    503: "Dependency unavailable",
}


def _slug(title: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in title.lower()).strip("-")


def problem(status: int, title: str, detail: str, request: Request, **extensions: Any) -> JSONResponse:
    """One problem+json response. Call it directly when translating an upstream failure:

        return problem(503, "Paging vendor unavailable", "Timed out after 3s.", request)
    """
    body: dict[str, Any] = {
        "type": f"{PROBLEM_TYPE_BASE}/{_slug(title)}",
        "title": title,
        "status": status,
        "detail": detail,
        "instance": request.url.path,
    }
    request_id = request.headers.get("X-Request-ID")
    if request_id:
        body["request_id"] = request_id
    body.update(extensions)
    return JSONResponse(body, status_code=status, media_type=PROBLEM_MEDIA_TYPE)


def install_problem_handlers(app: FastAPI) -> None:
    """Register the three handlers that make the shape universal."""

    @app.exception_handler(StarletteHTTPException)
    async def _http_exception(request: Request, exc: StarletteHTTPException) -> JSONResponse:
        title = _TITLES.get(exc.status_code, "Request failed")
        return problem(exc.status_code, title, str(exc.detail), request)

    @app.exception_handler(RequestValidationError)
    async def _validation_error(request: Request, exc: RequestValidationError) -> JSONResponse:
        errors = [
            {"loc": [str(part) for part in err.get("loc", ())], "msg": err.get("msg", "")}
            for err in exc.errors()
        ]
        return problem(
            422, "Validation failed", "The request failed validation.", request, errors=errors
        )

    @app.exception_handler(Exception)
    async def _unhandled(request: Request, exc: Exception) -> JSONResponse:
        # Never the exception text: it leaks internals to the caller. Log it instead.
        return problem(
            500, "Internal server error", "The request could not be completed.", request
        )
