#!/usr/bin/env python3
# Generated by scripts/generate_platform_adapters.py; do not edit.
"""Migrate one operational knowledge-update packet from schema v1 to v2."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Mapping, Sequence

import knowledge_update


def migrate(
    packet: Mapping[str, object],
    *,
    target_root: Path | None = None,
    allowed_knowledge_roots: Sequence[str] | None = None,
) -> dict[str, object]:
    """Return a deterministic, validated v2 copy without modifying *packet*."""

    return knowledge_update.migrate_v1_to_v2(
        packet,
        target_root=target_root,
        allowed_knowledge_roots=allowed_knowledge_roots,
    )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path, help="v1 knowledge-update JSON file")
    parser.add_argument(
        "--output",
        type=Path,
        help="write the canonical v2 packet to this new or existing file; default is stdout",
    )
    parser.add_argument(
        "--target-root",
        type=Path,
        help=(
            "target checkout for validating prepared dispositions and documentation "
            "duplicates (same as knowledge_update.py)"
        ),
    )
    parser.add_argument(
        "--allowed-knowledge-root",
        action="append",
        dest="allowed_knowledge_roots",
        help="caller-trusted documentation root; repeat per root (same as knowledge_update.py)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        packet = json.loads(args.path.read_text(encoding="utf-8"))
        if not isinstance(packet, dict):
            raise knowledge_update.KnowledgeUpdateValidationError(
                "knowledge update must be a JSON object"
            )
        migrated = migrate(
            packet,
            target_root=args.target_root,
            allowed_knowledge_roots=args.allowed_knowledge_roots,
        )
        payload = knowledge_update.canonical_json(migrated) + b"\n"
        if args.output is None:
            sys.stdout.buffer.write(payload)
        else:
            args.output.write_bytes(payload)
    except (
        OSError,
        json.JSONDecodeError,
        knowledge_update.KnowledgeUpdateValidationError,
    ) as exc:
        print(f"migration failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
