#!/usr/bin/env python3
# Generated by scripts/generate_platform_adapters.py; do not edit.
"""Run one fleet lane of an incident drill as a real plugin agent via ``claude -p``.

Each invocation is one node of the fleet graph: the prompt file is the inbound handoff packet and
the saved result is the outbound packet. Model, tools, cost, turns, and duration are recorded per
lane so a retro can account for them.

WHY THIS SCRIPT EXISTS rather than spawning subagents: a drill is only evidence about the fleet if
the lanes are the *real* plugin agents, with their real tool grants and the real hook guard. A
general-purpose subagent given an agent's markdown proves nothing about authority.

Usage (from the drill working directory)::

    python run_lane.py --step 01 --lane sre-triage --agent save-toolkit:sre \\
        --prompt-file prompts/01-sre-triage.md --allowed-tools "Read,Grep,Glob,Bash,Skill" \\
        --plugin-dir /path/to/checkout --cwd ./service

    python run_lane.py --step 02 --lane ic-declare --prompt-file prompts/02-ic.md \\
        --allowed-tools "Read,Grep,Glob,Skill"      # main session + skill, no --agent

Outputs land in ``--runs-dir`` (default ``runs/``) as ``<step>-<lane>.{md,stdout.json,stderr.txt,
meta.json}``.

Standard library only. Python 3.11+.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import shutil
import subprocess
import sys
import time


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--step", required=True, help="ordering key, e.g. 01 or 08b")
    parser.add_argument("--lane", required=True, help="short lane name used in output filenames")
    parser.add_argument("--agent", default=None, help="plugin agent, e.g. save-toolkit:sre; omit for a skill-driven main session")
    parser.add_argument("--prompt-file", required=True, type=pathlib.Path, help="the inbound handoff packet")
    parser.add_argument("--allowed-tools", default="Read,Grep,Glob,Skill", help="comma-separated tool allowlist for this lane")
    parser.add_argument("--model", default="claude-sonnet-5", help="pin the model; a drill records it as run conditions")
    parser.add_argument("--cwd", default=".", help="working directory for the lane (usually the drill's service copy)")
    parser.add_argument("--plugin-dir", default=None, help="fleet checkout to load as a plugin; defaults to CLAUDE_PLUGIN_DIR")
    parser.add_argument("--runs-dir", default="runs", type=pathlib.Path)
    parser.add_argument("--claude", default=None, help="path to the claude CLI; defaults to CLAUDE_CLI or PATH lookup")
    parser.add_argument("--python-dir", default=None, help="directory holding a real python3 for the plugin's guard hook; defaults to DRILL_PYTHON_DIR or this interpreter's directory")
    parser.add_argument("--timeout", type=int, default=900, help="seconds before the lane is abandoned")
    return parser.parse_args(argv)


def resolve_claude(explicit: str | None) -> str:
    candidate = explicit or os.environ.get("CLAUDE_CLI") or shutil.which("claude")
    if not candidate:
        raise SystemExit("cannot find the claude CLI: pass --claude or set CLAUDE_CLI")
    return candidate


def guard_path(explicit: str | None) -> str:
    """Directory to prepend to PATH so the plugin's read-only guard hook can run.

    The guard shim resolves ``python3``/``python``/``py`` from PATH and, when none answers with its
    exit codes, denies Bash for EVERY plugin agent — not just guarded ones. On Windows the bare
    names often resolve to the Microsoft Store stub, which silently strips a lane's shell.
    """
    return explicit or os.environ.get("DRILL_PYTHON_DIR") or str(pathlib.Path(sys.executable).parent)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    plugin_dir = args.plugin_dir or os.environ.get("CLAUDE_PLUGIN_DIR")
    if not plugin_dir:
        raise SystemExit("pass --plugin-dir (the fleet checkout to exercise) or set CLAUDE_PLUGIN_DIR")

    args.runs_dir.mkdir(parents=True, exist_ok=True)
    prompt = args.prompt_file.read_text(encoding="utf-8")

    argv_claude = [
        resolve_claude(args.claude), "-p",
        "--output-format", "json",
        "--no-session-persistence",
        "--plugin-dir", str(plugin_dir),
        "--mcp-config", '{"mcpServers":{}}',
        "--strict-mcp-config",
        "--model", args.model,
        "--allowedTools", *[t.strip() for t in args.allowed_tools.split(",") if t.strip()],
    ]
    if args.agent:
        argv_claude += ["--agent", args.agent]

    env = dict(os.environ)
    env.pop("CLAUDECODE", None)  # permit a nested non-interactive session
    py_dir = guard_path(args.python_dir)
    env["PATH"] = py_dir + os.pathsep + str(pathlib.Path(py_dir, "Scripts")) + os.pathsep + env.get("PATH", "")

    started = time.time()
    try:
        # The prompt goes over stdin: a handoff packet routinely exceeds Windows' 32K command-line
        # limit once it carries a diff plus a prior packet (observed: WinError 206 at 37 KB).
        proc = subprocess.run(
            argv_claude, cwd=args.cwd, capture_output=True, text=True, encoding="utf-8",
            errors="replace", env=env, timeout=args.timeout, input=prompt,
        )
    except subprocess.TimeoutExpired:
        print(json.dumps({"step": args.step, "lane": args.lane, "outcome": "TIMEOUT", "timeout_s": args.timeout}))
        return 124

    base = args.runs_dir / f"{args.step}-{args.lane}"
    base.with_suffix(".stdout.json").write_text(proc.stdout, encoding="utf-8")
    base.with_suffix(".stderr.txt").write_text(proc.stderr, encoding="utf-8")
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError:
        payload = {}
    result = payload.get("result") if isinstance(payload, dict) else None
    if isinstance(result, str):
        base.with_suffix(".md").write_text(result, encoding="utf-8")

    meta = {
        "step": args.step,
        "lane": args.lane,
        "agent": args.agent,
        "model_requested": args.model,
        "allowed_tools": args.allowed_tools,
        "plugin_dir": str(plugin_dir),
        "exit_code": proc.returncode,
        "duration_s": round(time.time() - started, 1),
        "total_cost_usd": payload.get("total_cost_usd") if isinstance(payload, dict) else None,
        "num_turns": payload.get("num_turns") if isinstance(payload, dict) else None,
        "is_error": payload.get("is_error") if isinstance(payload, dict) else None,
        "session_id": payload.get("session_id") if isinstance(payload, dict) else None,
    }
    base.with_suffix(".meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print(json.dumps(meta))
    print("----- result -----")
    print(result if isinstance(result, str) else proc.stdout[:2000])
    if proc.returncode != 0:
        print("----- stderr (tail) -----")
        print(proc.stderr[-1500:])
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
