#!/usr/bin/env python3
"""Render capped, grep-friendly views of the fleet atlas. One fact per line, stable IDs first."""

from __future__ import annotations

import re

BANNER = "<!-- generated by scripts/fleet_atlas.py; do not edit; regenerate with `python scripts/fleet_atlas.py build` -->"
VIEW_CAP = 20_000
INDEX_CAP = 4_000
TRUNCATED = "UNKNOWN: view truncated at 20000 bytes; use `python scripts/fleet_atlas.py query`"
MERMAID_SAFE = re.compile(r"[^A-Za-z0-9-]")

# Shape of a generated eval-evidence review doc (fleet_atlas_extract.EVAL_DOC_RE names the same
# pattern). Duplicated here rather than imported so this module stays a pure renderer of whatever
# document dict it is handed -- it never re-derives a fact, it only recognizes a REPEATING SHAPE
# among unknowns already emitted, purely to decide how to lay lines out.
GENERATED_EVAL_DOC_RE = re.compile(r"-eval-\d{8}T\d{6}Z-[0-9a-f]{8}\.md$")
COLLAPSE_THRESHOLD = 5  # a group larger than this many same-shaped items is summarized, not listed

QUESTIONS = (
    ("Which document is canonical for a fleet rule?", "grep the rule in decision-supersession-map.md; `query governs <phrase>`"),
    ("Which agent or skill owns a capability?", "capability-owner-map.md; `query owner-of <name>`"),
    ("Which references load for a task or predicate?", "skill-reference-loading-map.md; `query loads-for <skill> \"<predicate>\"`"),
    ("Which decision introduced or superseded a rule?", "decision-supersession-map.md; `query supersedes <decision>`"),
    ("Which roadmap item depends on another?", "roadmap-dependency-map.md; `query depends-on <ID>` (reverse: `query blocks <ID>`)"),
    ("Which eval or deterministic test verifies a claim?", "claim-to-eval-map.md; `query verified-by <node>`"),
    ("Which evidence report supports a roadmap status?", "`query evidence-for <ID>`"),
    ("Which generated adapters derive from a canonical source?", "`query generated-from <path>`"),
    ("Where do documentation, rules, roadmap status, and implementation claims disagree?", "contradictions-and-stale-evidence.md"),
    ("Which knowledge should be loaded for a question?", "this index; never atlas.json"),
    ("Which claims are stale, unverified, superseded, blocked, or missing evidence?", "contradictions-and-stale-evidence.md; `query state <node>`"),
)


def _head(document: dict, title: str) -> list[str]:
    """Header binds a view to the INPUTS it describes, never to the commit that contains it.

    A commit sha here made the drift gate permanently red: the atlas cannot embed the sha of the
    commit that will contain it, so every view drifted the instant it was committed (16 findings
    at HEAD). The input digest is also the more accurate binding — it changes when the canonical
    sources change and stays put when an unrelated commit lands, which is exactly what "is this
    view still describing the fleet?" means.
    """
    meta = document["metadata"]
    return [BANNER, f"# {title} — inputs {meta['treeDigest'][7:19]}", ""]


def _where(item: dict) -> str:
    evidence = item.get("evidence") or []
    return f"{evidence[0]['path']}:{evidence[0]['lines'][0]}" if evidence else "-"


def _cap(lines: list[str], cap: int) -> str:
    out: list[str] = []
    size = 0
    for line in lines:
        encoded = len(line.encode("utf-8")) + 1
        if size + encoded > cap:
            out.append(TRUNCATED)
            break
        out.append(line)
        size += encoded
    return "\n".join(out) + "\n"


def _edges(document: dict, *kinds: str) -> list[dict]:
    return sorted((e for e in document["edges"] if e["kind"] in kinds), key=lambda e: (e["source"], e["kind"], e["target"], e["id"]))


def _nodes(document: dict) -> dict[str, dict]:
    return {n["id"]: n for n in document["nodes"]}


def render_index(document: dict) -> str:
    lines = _head(document, "Fleet atlas index")
    lines += ["| Question | Answer surface |", "|---|---|"]
    lines += [f"| {q} | {a} |" for q, a in QUESTIONS]
    lines += ["", "Every fact line reads: source | edge | target | class | path:line. Classes CONTRACT_RESOLVED and",
              "STATIC_EXTRACTED render as [verified]; OPERATOR_CONFIRMED as [sourced]; STATIC_INFERRED and UNKNOWN as [unverified].",
              "The atlas cites delegation, guard, generated-projection, and prerequisite edges from the validators that",
              "enforce them; it never defines them. A contradiction here is a finding for a human, not a fact."]
    return _cap(lines, INDEX_CAP)


def _unknown_lines(items: list[dict]) -> list[str]:
    return [f"{u['code']} | {u['path']} | {u['message']} | needed: {u['neededEvidence']}" for u in items]


def _render_unknown_group(code: str, items: list[dict]) -> list[str]:
    # For each code: a header naming the total count, then every individually actionable entry, one
    # line per fact. When a subset shares one repeating shape (today: uncited generated eval-evidence
    # review docs, *-eval-<batch>.md, all with the same detector, same needed evidence, and only the
    # batch id differing), that subset collapses into one summary line naming the pattern and count
    # plus at most COLLAPSE_THRESHOLD examples, followed by a line stating how many were elided.
    # Nothing is silently dropped: the elided count always appears.
    items = sorted(items, key=lambda u: (u["path"] or "", u["message"]))
    generated = [u for u in items if GENERATED_EVAL_DOC_RE.search(u["path"] or "")]
    individual = [u for u in items if u not in generated]
    lines = [f"## {code} ({len(items)})"]
    lines += _unknown_lines(individual)
    if len(generated) > COLLAPSE_THRESHOLD:
        examples = ", ".join(u["path"].rsplit("/", 1)[-1] for u in generated[:COLLAPSE_THRESHOLD])
        lines.append(f"{code} | pattern: uncited generated eval-evidence review (*-eval-<batch>.md) | "
                     f"{len(generated)} matching | examples: {examples}")
        lines.append(f"{code} | elided {len(generated)} generated eval-evidence docs of this identical shape "
                     "from individual lines; regenerate the batch's review or see docs/reviews/*-eval-*.md")
    else:
        lines += _unknown_lines(generated)
    return lines


def render_views(document: dict) -> dict[str, str]:
    views: dict[str, str] = {"INDEX.md": render_index(document)}

    lines = _head(document, "Capability and owner map")
    for e in _edges(document, "owns", "delegates_to", "constrained_by"):
        lines.append(f"{e['source']} | {e['kind']} | {e['target']} | {e['class']} | {_where(e)}")
    views["capability-owner-map.md"] = _cap(lines, VIEW_CAP)

    lines = _head(document, "Skill and reference loading map")
    for e in _edges(document, "loads_when"):
        lines.append(f"{e['source']} | loads_when | {e['target']} | \"{e['attrs'].get('predicate', 'UNKNOWN')}\" | {_where(e)}")
    views["skill-reference-loading-map.md"] = _cap(lines, VIEW_CAP)

    lines = _head(document, "Claim to eval and test map")
    for e in _edges(document, "verified_by", "near_miss_for"):
        via = e["attrs"].get("mode") or e["attrs"].get("via") or e["attrs"].get("expected_alternative") or "-"
        lines.append(f"{e['source']} | {e['kind']} | {e['target']} | {via} | {_where(e)}")
    views["claim-to-eval-map.md"] = _cap(lines, VIEW_CAP)

    lines = _head(document, "Decision and supersession map")
    for n in sorted((n for n in document["nodes"] if n["type"] == "decision"), key=lambda n: n["id"]):
        lines.append(f"{n['id']} | {n['state']} | {n['attrs'].get('date', '')} | {n['authority']} | {n['path']}")
    for e in _edges(document, "supersedes", "governed_by"):
        lines.append(f"{e['source']} | {e['attrs'].get('relation', e['kind'])} | {e['target']} | {e['class']} | {_where(e)}")
    for u in document["unknowns"]:
        if u["code"].startswith("extract.supersedes") or u["code"].startswith("extract.rule-source"):
            lines.append(f"UNKNOWN | {u['code']} | {u['path']} | {u['message']}")
    views["decision-supersession-map.md"] = _cap(lines, VIEW_CAP)

    lines = _head(document, "Roadmap dependency map")
    for n in sorted((n for n in document["nodes"] if n["type"] == "roadmap-item"), key=lambda n: n["id"]):
        lines.append(f"{n['id']} | {n['state']} | {n['attrs'].get('status', n['attrs'].get('closed', ''))} | {n['attrs'].get('owner', '')[:60]}".rstrip())
    for e in _edges(document, "depends_on"):
        lines.append(f"{e['source']} | depends_on | {e['target']} | {e['class']} ({e['attrs'].get('field', '')}) | {_where(e)}")
    views["roadmap-dependency-map.md"] = _cap(lines, VIEW_CAP)

    lines = _head(document, "Contradictions and stale evidence")
    for e in _edges(document, "contradicts"):
        lines.append(f"contradicts | {e['attrs']['detector']} | {e['source']} -> {e['target']} | {e['attrs']['message']} | {_where(e)}")
    by_code: dict[str, list[dict]] = {}
    for u in document["unknowns"]:
        by_code.setdefault(u["code"], []).append(u)
    for code in sorted(by_code):
        lines += _render_unknown_group(code, by_code[code])
    views["contradictions-and-stale-evidence.md"] = _cap(lines, VIEW_CAP)

    def mermaid(kind: str) -> str:
        body = [BANNER.replace("<!--", "%%").replace("-->", "").rstrip(), "graph LR"]
        for e in _edges(document, kind):
            a = MERMAID_SAFE.sub("_", e["source"].split(":", 1)[1])
            b = MERMAID_SAFE.sub("_", e["target"].split(":", 1)[1])
            body.append(f"  {a} --> {b}")
        return "\n".join(body) + "\n"

    views["roadmap-dependency-map.mmd"] = mermaid("depends_on")
    views["delegation.mmd"] = mermaid("delegates_to")
    return views
