#!/usr/bin/env python3
"""Generate Copilot/VS Code, Codex, and Cursor adapters from canonical plugin sources.

``agents/*.md`` and ``skills/**`` are the only authored fleet definitions. Claude Code reads
them directly from the plugin. Other hosts have different agent schemas and enforcement limits,
so their projections are generated, committed, and checked byte-for-byte.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import tempfile
from pathlib import Path


COPILOT_AGENTS = Path(".github/agents")
CODEX_AGENTS = Path(".codex/agents")
COPILOT_SKILLS = Path("platforms/copilot/skills")
CODEX_PLUGIN_ROOT = Path("plugins/sre-agents")
CODEX_SKILLS = CODEX_PLUGIN_ROOT / "skills"
CURSOR_AGENTS = Path(".cursor/agents")
CURSOR_SKILLS = Path(".cursor/skills")
GENERATED_ROOTS = (COPILOT_AGENTS, CODEX_AGENTS, COPILOT_SKILLS, CODEX_SKILLS, CURSOR_AGENTS, CURSOR_SKILLS)
GENERATED_MARKER = "Generated by scripts/generate_platform_adapters.py; do not edit."
MANUAL_ONLY = {"pcf-deploy", "service-onboarding"}
GUARDED_AGENTS = {"sre", "sre-steward"}
LOCAL_ONLY_AGENTS = {"repository-investigator", "scribe"}
EXTERNAL_ONLY_AGENTS = {"researcher"}
# Cursor documents exactly these skill frontmatter fields (https://cursor.com/docs/skills).
# Canonical skills also carry Claude-side metadata (`argument-hint`, `compatibility`), which the
# Cursor projection drops rather than feeds a host whose unknown-field handling is undocumented.
CURSOR_SKILL_FIELDS = ("name", "description", "paths", "globs", "disable-model-invocation", "metadata")

COPILOT_TOOL_ORDER = ("read", "search", "edit", "execute", "web", "agent")
COPILOT_TOOL_MAP = {
    "Read": "read",
    "Grep": "search",
    "Glob": "search",
    "Write": "edit",
    "Edit": "edit",
    "NotebookEdit": "edit",
    "Bash": "execute",
    "WebFetch": "web",
    "WebSearch": "web",
    "Agent": "agent",
}
WRITE_TOOLS = {"Write", "Edit", "NotebookEdit"}
IDENTITY_FIELDS = (
    "name", "version", "description", "author", "homepage", "repository", "license", "keywords"
)

KEY_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):(?:[ \t]*(.*))?$")
PLUGIN_TOKEN_RE = re.compile(r"(?<![A-Za-z0-9_-])sre-agents:(?=[a-z0-9])")
# Codex resolves a custom agent by its `name` field, not its filename, so the fleet boundary has
# to live in the identity as well as the file. Skills are NOT renamed, so only agent tokens are
# rewritten; everything else keeps falling through to the bare-name strip above.
CODEX_AGENT_PREFIX = "sre-agents-"
PLUGIN_COMPONENT_RE = re.compile(r"(?<![A-Za-z0-9_-])sre-agents:([a-z0-9][a-z0-9-]*)")
PLUGIN_PATH_RE = re.compile(
    r"`?\$\{CLAUDE_PLUGIN_ROOT\}/(?P<kind>skills|agents)/"
    r"(?P<name>[a-z0-9]+(?:-[a-z0-9]+)*)(?P<tail>/[^`\s]+|\.md)?`?"
)
RUNTIME_SUFFIXES = {".pyc", ".pyo"}


def _yaml_scalar(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith('"'):
        return json.loads(raw)
    if raw.startswith("'") and raw.endswith("'"):
        return raw[1:-1].replace("''", "'")
    return raw


def parse_frontmatter(path: Path) -> tuple[dict[str, object], str, list[str]]:
    """Parse the deliberately small YAML subset used by this repository."""

    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing opening frontmatter marker")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration as exc:
        raise ValueError(f"{path}: missing closing frontmatter marker") from exc

    values: dict[str, object] = {}
    raw_lines = lines[1:end]
    index = 0
    while index < len(raw_lines):
        line = raw_lines[index]
        if not line.strip() or line.lstrip().startswith("#"):
            index += 1
            continue
        match = KEY_RE.fullmatch(line)
        if not match:
            raise ValueError(f"{path}:{index + 2}: unsupported frontmatter syntax")
        key, raw = match.group(1), (match.group(2) or "")
        if key in values:
            raise ValueError(f"{path}:{index + 2}: duplicate frontmatter key {key!r}")
        if raw in {">", ">-", "|", "|-"}:
            folded: list[str] = []
            index += 1
            while index < len(raw_lines) and (
                not raw_lines[index] or raw_lines[index].startswith((" ", "\t"))
            ):
                folded.append(raw_lines[index].strip())
                index += 1
            values[key] = " ".join(part for part in folded if part)
            continue
        if not raw:
            items: list[str] = []
            index += 1
            while index < len(raw_lines):
                item = re.fullmatch(r"\s+-\s+(.+?)\s*", raw_lines[index])
                if not item:
                    break
                items.append(_yaml_scalar(item.group(1)))
                index += 1
            values[key] = items
            continue
        values[key] = _yaml_scalar(raw)
        index += 1

    body = "\n".join(lines[end + 1 :]).lstrip("\n")
    if text.endswith("\n"):
        body += "\n"
    return values, body, raw_lines


def _split_tool_specs(raw: object) -> list[str]:
    if isinstance(raw, list):
        return [str(item).strip() for item in raw if str(item).strip()]
    text = str(raw or "")
    result: list[str] = []
    start = 0
    depth = 0
    for index, char in enumerate(text):
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            result.append(text[start:index].strip())
            start = index + 1
    if text[start:].strip():
        result.append(text[start:].strip())
    return result


def _tool_base(spec: str) -> str:
    return spec.split("(", 1)[0].strip()


def _installed_resource(match: re.Match[str]) -> str:
    kind, name, tail = match.group("kind"), match.group("name"), match.group("tail")
    if kind == "agents":
        return f"the installed `{name}` agent definition"
    if not tail or tail == "/SKILL.md":
        return f"the installed `{name}` skill"
    return f"the installed `{name}` skill's `{tail.lstrip('/')}` resource"


def _canonical_agent_names(root: Path) -> frozenset[str]:
    return frozenset(path.stem for path in (root / "agents").glob("*.md"))


def adapt_text(text: str, host: str, *, agent_names: frozenset[str] = frozenset()) -> str:
    """Remove Claude-only runtime addressing while preserving the authored method.

    ``agent_names`` namespaces sibling-agent references for Codex, which resolves an agent by
    its bare name in one shared global directory. Every Codex output routes through here, so
    this is the single place that has to know about it.
    """

    if host not in {"copilot", "codex", "cursor"}:
        raise ValueError(f"unknown host {host!r}")
    if host == "codex" and agent_names:
        text = _codex_component_tokens(text, agent_names)
    text = text.replace(
        "> **Plugin addressing:** In Claude, invoke every fleet agent or skill named below as "
        "`sre-agents:<component>`; generated adapters use the target host's bare component names.\n\n",
        "",
    )
    text = PLUGIN_TOKEN_RE.sub("", text)
    text = PLUGIN_PATH_RE.sub(_installed_resource, text)
    text = text.replace("`.claude/agents/", "`agents/")
    text = text.replace("`.claude/skills/", "`skills/")
    text = text.replace("`.claude/commands/", "`commands/")
    if host == "codex":
        # Only rewrite known skill invocation tokens. A generic `/name` rewrite corrupts API
        # paths, URLs, OpenAPI `$ref` values, and filesystem examples.
        for name in sorted(MANUAL_ONLY):
            text = re.sub(
                rf"(?<![A-Za-z0-9_/-])/{re.escape(name)}(?![A-Za-z0-9_-])",
                f"${name}",
                text,
            )
    return text


def _description(fields: dict[str, object], source: Path) -> str:
    description = fields.get("description")
    if not isinstance(description, str) or not description.strip():
        raise ValueError(f"{source}: missing description")
    return description.strip()


def render_copilot_agent(source: Path) -> str:
    fields, body, _ = parse_frontmatter(source)
    name = str(fields.get("name") or "")
    tools = {_tool_base(item) for item in _split_tool_specs(fields.get("tools"))}
    has_external_evidence = any(item.startswith("mcp__") for item in _split_tool_specs(fields.get("tools")))
    mapped = {COPILOT_TOOL_MAP[item] for item in tools if item in COPILOT_TOOL_MAP}
    if name in GUARDED_AGENTS:
        mapped.discard("execute")
    ordered = [tool for tool in COPILOT_TOOL_ORDER if tool in mapped]
    contract = [
        "## Host adapter contract",
        "",
        "This generated profile runs on GitHub Copilot and VS Code. Fleet component names are",
        "bare on these hosts; resolve them through the installed plugin's agent or skill picker.",
    ]
    if name in GUARDED_AGENTS:
        contract += [
            "",
            "This profile deliberately receives no shell/execute tool. Claude's source profile",
            "uses a session-wide read-only Bash guard, but these hosts cannot enforce that same",
            "agent-specific command allowlist from the plugin contract.",
        ]
    if has_external_evidence:
        contract += [
            "",
            "The canonical Claude role has exact read-only Context7/GitHits grants. This host",
            "adapter cannot declare those Claude MCP identifiers; use equivalent installed read-only",
            "evidence tools when present, otherwise report the unavailable evidence lane explicitly.",
        ]
    return (
        "---\n"
        f"name: {json.dumps(name, ensure_ascii=False)}\n"
        f"description: {json.dumps(adapt_text(_description(fields, source), 'copilot'), ensure_ascii=False)}\n"
        f"tools: {json.dumps(ordered)}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n"
        + "\n".join(contract)
        + "\n\n"
        + adapt_text(body, "copilot")
    )


def render_cursor_agent(source: Path) -> str:
    """Render one canonical agent as a Cursor project subagent (`.cursor/agents/<name>.md`).

    Cursor's subagent schema is exactly `name`, `description`, `model`, `readonly`,
    `is_background` (https://cursor.com/docs/subagents). The fleet pins no model and runs no
    background-only roles, so only `name`, `description`, and an explicit `readonly` are emitted;
    `readonly` is the single tool-posture knob Cursor has, and it is derived from whether the
    canonical role may write files or run a shell at all.
    """

    fields, body, _ = parse_frontmatter(source)
    name = str(fields.get("name") or "")
    specs = _split_tool_specs(fields.get("tools"))
    tools = {_tool_base(item) for item in specs}
    has_external_evidence = any(item.startswith("mcp__") for item in specs)
    readonly = not (tools & (WRITE_TOOLS | {"Bash"}))
    contract = [
        "## Host adapter contract",
        "",
        "This generated profile runs on Cursor as a project subagent. Fleet component names are",
        "bare on this host; invoke them with `/name` or the agent and skill pickers. Cursor",
        "shares one `/` namespace across subagents, skills, and commands, so fleet component",
        "names are unique across those kinds. Installed at user level, these profiles share one",
        "flat global agents directory with every other suite; project scope is the",
        "collision-free install.",
    ]
    if name in GUARDED_AGENTS:
        contract += [
            "",
            "The canonical Claude role runs Bash under a session-wide read-only command allowlist.",
            "Cursor's `beforeShellExecution` hook receives no agent identity, so no per-agent shell",
            "guard can be projected: this profile inherits an unguarded shell. The allowlist's",
            "read-only discipline below is a body rule here, not an enforced boundary; run this",
            "role on a host that enforces it when the boundary is load-bearing.",
        ]
    if name in LOCAL_ONLY_AGENTS and not readonly:
        contract += [
            "",
            "This role may edit files but must never run a shell. Cursor has no per-agent shell",
            "denial short of `readonly` (which would also block edits), so the no-shell boundary",
            "is cooperative on this host.",
        ]
    if name in EXTERNAL_ONLY_AGENTS:
        contract += [
            "",
            "Cursor's `readonly` blocks edits and state-changing shell commands, but not local",
            "file reads or web tools. This external-only role's local-read boundary is",
            "cooperative on this host; enforce it with workspace or mount isolation when it is",
            "load-bearing.",
        ]
    if has_external_evidence:
        contract += [
            "",
            "The canonical Claude role has exact read-only Context7/GitHits grants. Cursor has no",
            "per-agent tool allowlist to declare them; use equivalent installed read-only",
            "evidence tools when present, otherwise report the unavailable evidence lane",
            "explicitly.",
        ]
    return (
        "---\n"
        f"name: {json.dumps(name, ensure_ascii=False)}\n"
        f"description: {json.dumps(adapt_text(_description(fields, source), 'cursor'), ensure_ascii=False)}\n"
        f"readonly: {'true' if readonly else 'false'}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER} -->\n\n"
        + "\n".join(contract)
        + "\n\n"
        + adapt_text(body, "cursor")
    )


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _codex_component_tokens(text: str, agent_names: frozenset[str]) -> str:
    """Rewrite `sre-agents:<agent>` to the prefixed Codex identity; leave skills alone."""

    text = PLUGIN_COMPONENT_RE.sub(
        lambda match: (
            f"{CODEX_AGENT_PREFIX}{match.group(1)}"
            if match.group(1) in agent_names
            else match.group(1)
        ),
        text,
    )
    # Canonical bodies also name siblings as bare backticked identifiers (`reviewer`). Those must
    # move with the identity or they resolve to whoever else owns that name in the shared global
    # directory. ONLY backticked occurrences are rewritten -- prose ("the SRE lens", "an sde task")
    # must not move, and longest-first keeps `sre` from reaching inside `sre-steward`.
    for agent in sorted(agent_names, key=len, reverse=True):
        text = text.replace(f"`{agent}`", f"`{CODEX_AGENT_PREFIX}{agent}`")
    return text


def render_codex_agent(source: Path) -> str:
    fields, body, _ = parse_frontmatter(source)
    name = str(fields.get("name") or "")
    siblings = frozenset(path.stem for path in source.parent.glob("*.md"))
    tools = {_tool_base(item) for item in _split_tool_specs(fields.get("tools"))}
    has_external_evidence = any(item.startswith("mcp__") for item in _split_tool_specs(fields.get("tools")))
    sandbox = "workspace-write" if tools & WRITE_TOOLS else "read-only"
    if "'''" in body:
        raise ValueError(f"{source}: body contains TOML multiline-string terminator")
    contract = (
        "Host adapter contract:\n"
        "- This generated profile is a standalone Codex custom agent. Fleet component names are\n"
        "  bare; select skills with Codex's skill picker or `$name` syntax.\n"
        "- This fleet's agents are named and installed as `sre-agents-<role>`; Codex resolves a\n"
        "  custom agent by its `name` field, and the flat global agents directory is shared with\n"
        "  every other installed suite. Spawn a fleet sibling by its prefixed name; an unprefixed\n"
        "  role name may belong to somebody else's agents.\n"
        "- Parent session permissions can override this requested sandbox.\n"
        "- Codex custom-agent TOML has no per-agent tool allowlist; inherited shell, MCP, skill,\n"
        "  and subagent capabilities can be wider than the canonical Claude profile.\n"
        f"- This adapter requests `sandbox_mode = \"{sandbox}\"`; treat narrower tool rules in the\n"
        "  body as cooperative unless an outer boundary enforces them.\n\n"
    )
    if has_external_evidence:
        contract += (
            "- The canonical Claude role grants exact read-only Context7/GitHits tools. Codex may\n"
            "  inherit equivalent plugin tools from the parent, but this TOML cannot require them;\n"
            "  report that evidence lane unavailable rather than pretending it ran.\n\n"
        )
    if name in LOCAL_ONLY_AGENTS:
        contract += (
            "- This is a local-only role. Because Codex cannot deny inherited tools per custom agent,\n"
            "  enforce the boundary outside the profile: disable network egress and external MCP tools.\n\n"
        )
    if name in EXTERNAL_ONLY_AGENTS:
        contract += (
            "- This is an external-only role. Because Codex cannot deny inherited tools per custom agent,\n"
            "  enforce the boundary outside the profile: do not mount the private repository and expose\n"
            "  only approved external evidence tools.\n\n"
        )
    return (
        f"# {GENERATED_MARKER}\n"
        f"name = {_toml_string(CODEX_AGENT_PREFIX + name)}\n"
        f"description = {_toml_string(adapt_text(_description(fields, source), 'codex', agent_names=siblings))}\n"
        f"sandbox_mode = {_toml_string(sandbox)}\n"
        "developer_instructions = '''\n"
        + contract
        + adapt_text(body, "codex", agent_names=siblings)
        + "'''\n"
    )


def _cursor_skill_frontmatter(
    raw_lines: list[str], fields: dict[str, object]
) -> tuple[list[str], list[str]]:
    """Keep only Cursor-documented skill fields, dropping whole key blocks (values included)."""

    kept: list[str] = []
    current_key: str | None = None
    for line in raw_lines:
        key_match = KEY_RE.fullmatch(line)
        if key_match:
            current_key = key_match.group(1)
        if current_key is not None and current_key not in CURSOR_SKILL_FIELDS:
            continue
        kept.append(line)
    dropped = sorted(key for key in fields if key not in CURSOR_SKILL_FIELDS)
    return kept, dropped


def _portable_skill(
    source: Path, host: str, *, agent_names: frozenset[str] = frozenset()
) -> tuple[bytes, bool]:
    fields, body, raw_lines = parse_frontmatter(source)
    explicit = str(fields.get("name")) in MANUAL_ONLY or fields.get("disable-model-invocation") == "true"
    dropped: list[str] = []
    if host == "cursor":
        kept, dropped = _cursor_skill_frontmatter(raw_lines, fields)
    else:
        kept = []
        for line in raw_lines:
            if host == "codex" and line.startswith("disable-model-invocation:"):
                continue
            kept.append(line)
    portable_frontmatter = adapt_text("\n".join(kept), host, agent_names=agent_names)
    if host == "cursor":
        note = [
            "> **Cursor adapter:** Fleet component names are bare in this generated copy. Resolve",
            "> them via Cursor's skill or agent picker (`/name`).",
        ]
    else:
        note = [
            f"> **{host.capitalize()} adapter:** Fleet component names are bare in this generated copy.",
            "> Resolve them from the installed plugin using the host's agent or skill picker.",
        ]
    if explicit:
        control = (
            "Copilot's frontmatter switch" if host == "copilot"
            else "Cursor's `disable-model-invocation: true` frontmatter" if host == "cursor"
            else "the generated `agents/openai.yaml` policy"
        )
        note.append(f"> This skill is explicit-only through {control}.")
    if dropped:
        rendered_dropped = ", ".join(f"`{key}`" for key in dropped)
        note.append(
            f"> Claude-only frontmatter ({rendered_dropped}) is omitted: Cursor documents only"
            " name, description, paths/globs, disable-model-invocation, and metadata for skills."
        )
    rendered = (
        "---\n"
        + portable_frontmatter
        + "\n---\n\n"
        + f"<!-- {GENERATED_MARKER} -->\n\n"
        + "\n".join(note)
        + "\n\n"
        + adapt_text(body, host, agent_names=agent_names)
    )
    return rendered.encode("utf-8"), explicit


def _skill_policy(name: str, description: str) -> bytes:
    display = " ".join(part.capitalize() for part in name.split("-"))
    short = description if len(description) <= 100 else description[:97].rstrip() + "..."
    return (
        "interface:\n"
        f"  display_name: {json.dumps(display, ensure_ascii=False)}\n"
        f"  short_description: {json.dumps(short, ensure_ascii=False)}\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    ).encode("utf-8")


def _is_runtime_byproduct(path: Path) -> bool:
    return "__pycache__" in path.parts or path.suffix.lower() in RUNTIME_SUFFIXES


def _is_link_or_reparse(path: Path) -> bool:
    if path.is_symlink():
        return True
    try:
        attrs = getattr(path.lstat(), "st_file_attributes", 0)
    except OSError:
        return False
    return bool(attrs & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0))


def _assert_no_indirection_below(root: Path, path: Path, label: str) -> None:
    """Reject links/reparse points in every existing component below ``root``.

    Checking only the leaf is insufficient: a normal-looking ``.github/agents`` directory can
    still escape the repository when ``.github`` itself is a junction or symlink.
    """

    root = root.resolve()
    try:
        relative = path.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"{path}: {label} must remain below {root}") from exc
    current = root
    for component in relative.parts:
        current /= component
        if (current.exists() or current.is_symlink()) and _is_link_or_reparse(current):
            raise ValueError(f"{current}: {label} must not traverse a link/reparse point")


def _canonical_skill_files(root: Path) -> list[Path]:
    result: list[Path] = []
    skill_root = root / "skills"
    _assert_no_indirection_below(root, skill_root, "canonical source")
    for current, directories, files in os.walk(skill_root, followlinks=False):
        current_path = Path(current)
        if _is_link_or_reparse(current_path):
            raise ValueError(f"{current_path}: canonical source must not be a link/reparse point")
        for directory in list(directories):
            child = current_path / directory
            if _is_link_or_reparse(child):
                raise ValueError(f"{child}: canonical source must not be a link/reparse point")
        for filename in files:
            path = current_path / filename
            if _is_runtime_byproduct(path):
                continue
            if _is_link_or_reparse(path):
                raise ValueError(f"{path}: canonical source must not be a link/reparse point")
            result.append(path)
    return sorted(result)


def expected_outputs(root: Path) -> dict[Path, bytes]:
    root = root.resolve()
    outputs: dict[Path, bytes] = {}
    _assert_no_indirection_below(root, root / "agents", "canonical source")
    _assert_no_indirection_below(root, root / "skills", "canonical source")
    agents = sorted((root / "agents").glob("*.md"))
    if not agents:
        raise ValueError(f"{root / 'agents'}: no canonical agents found")
    for source in agents:
        if _is_link_or_reparse(source):
            raise ValueError(f"{source}: canonical source must not be a link/reparse point")
        outputs[COPILOT_AGENTS / f"{source.stem}.agent.md"] = render_copilot_agent(source).encode("utf-8")
        # Codex custom agents are flat files in ONE global directory with no per-plugin
        # namespace, so the filename is the only place a fleet boundary can live. Claude loads
        # the same components as `sre-agents:<name>`; this mirrors that namespace so installing
        # the fleet cannot overwrite an identically-named agent from someone else's suite.
        outputs[CODEX_AGENTS / f"sre-agents-{source.stem}.toml"] = render_codex_agent(
            source
        ).encode("utf-8")
        # Cursor project subagents are project-scoped (`.cursor/agents/`), so bare filenames
        # cannot collide across suites here; the shared-`/`-namespace rule is a contract check.
        outputs[CURSOR_AGENTS / f"{source.stem}.md"] = render_cursor_agent(source).encode("utf-8")

    agent_names = _canonical_agent_names(root)
    skill_files = _canonical_skill_files(root)
    if not any(path.name == "SKILL.md" for path in skill_files):
        raise ValueError(f"{root / 'skills'}: no canonical skills found")
    for source in skill_files:
        relative = source.relative_to(root / "skills")
        if source.name == "SKILL.md":
            copilot, _ = _portable_skill(source, "copilot")
            codex, explicit = _portable_skill(source, "codex", agent_names=agent_names)
            cursor, _ = _portable_skill(source, "cursor", agent_names=agent_names)
            outputs[COPILOT_SKILLS / relative] = copilot
            outputs[CODEX_SKILLS / relative] = codex
            outputs[CURSOR_SKILLS / relative] = cursor
            if explicit:
                fields, _, _ = parse_frontmatter(source)
                outputs[CODEX_SKILLS / relative.parent / "agents/openai.yaml"] = _skill_policy(
                    str(fields["name"]), _description(fields, source)
                )
            continue
        content = source.read_bytes()
        if source.suffix.lower() in {".md", ".txt", ".yaml", ".yml", ".json"}:
            text = source.read_text(encoding="utf-8")
            outputs[COPILOT_SKILLS / relative] = adapt_text(text, "copilot").encode("utf-8")
            outputs[CODEX_SKILLS / relative] = adapt_text(
                text, "codex", agent_names=agent_names
            ).encode("utf-8")
            outputs[CURSOR_SKILLS / relative] = adapt_text(
                text, "cursor", agent_names=agent_names
            ).encode("utf-8")
        else:
            outputs[COPILOT_SKILLS / relative] = content
            outputs[CODEX_SKILLS / relative] = content
            outputs[CURSOR_SKILLS / relative] = content
    return outputs


def _actual_generated_files(root: Path) -> set[Path]:
    actual: set[Path] = set()
    for relative in GENERATED_ROOTS:
        base = root / relative
        _assert_no_indirection_below(root, base, "generated output")
        if not base.exists():
            continue
        if _is_link_or_reparse(base):
            raise ValueError(f"{base}: generated root must not be a link/reparse point")
        for current, directories, files in os.walk(base, followlinks=False):
            current_path = Path(current)
            for directory in list(directories):
                child = current_path / directory
                if _is_link_or_reparse(child):
                    raise ValueError(f"{child}: generated output must not be a link/reparse point")
            for filename in files:
                path = current_path / filename
                if _is_runtime_byproduct(path):
                    continue
                if _is_link_or_reparse(path):
                    raise ValueError(f"{path}: generated output must not be a link/reparse point")
                actual.add(path.relative_to(root))
    return actual


def validate_generated_outputs(root: Path) -> list[str]:
    try:
        expected = expected_outputs(root)
        actual = _actual_generated_files(root.resolve())
    except (OSError, UnicodeError, ValueError) as exc:
        return [str(exc)]
    failures: list[str] = []
    for path in sorted(set(expected) - actual):
        failures.append(f"{path.as_posix()}: generated output is missing; run adapter generator --write")
    for path in sorted(actual - set(expected)):
        failures.append(f"{path.as_posix()}: stale generated output")
    for relative in sorted(set(expected) & actual):
        if (root / relative).read_bytes() != expected[relative]:
            failures.append(f"{relative.as_posix()}: generated output drift")
    return failures


def _manifest(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: manifest must be a JSON object")
    return value


def cursor_namespace_failures(root: Path) -> list[str]:
    """Cursor contract: one shared `/` namespace, and skill name must equal its folder name.

    Cursor invokes subagents, skills, and legacy commands through a single `/name` namespace
    (https://cursor.com/docs/subagents), and requires a skill's frontmatter `name` to match the
    folder containing its SKILL.md (https://cursor.com/docs/skills).
    """

    failures: list[str] = []
    agent_names = {path.stem for path in (root / "agents").glob("*.md")}
    skill_names: set[str] = set()
    for skill in sorted((root / "skills").rglob("SKILL.md")):
        folder = skill.parent.name
        try:
            fields, _, _ = parse_frontmatter(skill)
        except (OSError, UnicodeError, ValueError) as exc:
            failures.append(str(exc))
            continue
        if fields.get("name") != folder:
            failures.append(
                f"{skill}: Cursor requires the skill name {fields.get('name')!r}"
                f" to match its folder {folder!r}"
            )
        skill_names.add(folder)
    collisions = sorted(agent_names & skill_names)
    if collisions:
        failures.append(
            "Cursor shares one `/` namespace across subagents, skills, and commands;"
            " agent/skill name collisions: " + ", ".join(collisions)
        )
    return failures


def validate_platform_contracts(root: Path) -> list[str]:
    failures: list[str] = []
    failures.extend(cursor_namespace_failures(root))
    paths = [root / ".claude-plugin/plugin.json", root / "plugin.json", root / "plugins/sre-agents/.codex-plugin/plugin.json"]
    manifests: list[dict] = []
    for path in paths:
        try:
            manifests.append(_manifest(path))
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            failures.append(str(exc))
    if len(manifests) == len(paths):
        baseline = manifests[0]
        for field in IDENTITY_FIELDS:
            for path, manifest in zip(paths[1:], manifests[1:]):
                if manifest.get(field) != baseline.get(field):
                    failures.append(f"{path}: identity field {field!r} differs from Claude manifest")
        copilot = manifests[1]
        expected_components = {
            "agents": "./.github/agents/",
            "skills": "./platforms/copilot/skills/",
            "hooks": "./hooks/copilot-hooks.json",
        }
        for field, expected in expected_components.items():
            if copilot.get(field) != expected:
                failures.append(f"plugin.json: {field} must be {expected!r}")
        codex = manifests[2]
        if codex.get("skills") != "./skills/":
            failures.append("Codex manifest skills must be './skills/'")
        for forbidden in ("agents", "hooks"):
            if forbidden in codex:
                failures.append(f"Codex manifest must not claim unsupported {forbidden!r} component")
    try:
        hook = _manifest(root / "hooks/hooks.json")
        command = hook["hooks"]["PreToolUse"][0]["hooks"][0]["command"]
        for token in ("${CLAUDE_PLUGIN_ROOT}", "readonly-guard.py", "python3 python py"):
            if token not in command:
                failures.append(f"hooks/hooks.json: command is missing {token!r}")
        if 'case "$IN"' in command:
            failures.append("hooks/hooks.json: raw-JSON prefilter bypasses the Python identity canary")
    except (OSError, json.JSONDecodeError, KeyError, IndexError, TypeError, ValueError) as exc:
        failures.append(f"hooks/hooks.json: invalid hook contract: {exc}")
    return failures


def validate_platform_support(root: Path) -> list[str]:
    return validate_platform_contracts(root) + validate_generated_outputs(root)


def write_generated_outputs(root: Path) -> int:
    root = root.resolve()
    outputs = expected_outputs(root)
    for relative in GENERATED_ROOTS:
        target = root / relative
        _assert_no_indirection_below(root, target, "generated root")
        if target.exists() and _is_link_or_reparse(target):
            raise ValueError(f"{target}: refusing to replace a link/reparse point")

    with tempfile.TemporaryDirectory(prefix=".adapter-stage-", dir=root) as temporary:
        stage = Path(temporary) / "new"
        backup = Path(temporary) / "old"
        for relative, content in outputs.items():
            destination = stage / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)

        moved: list[tuple[Path, Path | None]] = []
        try:
            for relative in GENERATED_ROOTS:
                destination = root / relative
                staged = stage / relative
                saved: Path | None = None
                if destination.exists():
                    saved = backup / relative
                    saved.parent.mkdir(parents=True, exist_ok=True)
                    os.replace(destination, saved)
                destination.parent.mkdir(parents=True, exist_ok=True)
                try:
                    os.replace(staged, destination)
                except OSError:
                    # The current root has already moved. Restore this iteration before the outer
                    # rollback handles roots that completed earlier; otherwise TemporaryDirectory
                    # cleanup would delete the only backup.
                    if saved is not None and saved.exists() and not destination.exists():
                        os.replace(saved, destination)
                    raise
                moved.append((destination, saved))
        except OSError:
            for destination, saved in reversed(moved):
                if destination.exists():
                    shutil.rmtree(destination)
                if saved is not None and saved.exists():
                    destination.parent.mkdir(parents=True, exist_ok=True)
                    os.replace(saved, destination)
            raise
    return len(outputs)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="replace generated roots transactionally")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    try:
        contract_failures = validate_platform_contracts(root)
        if contract_failures:
            for failure in contract_failures:
                print(failure)
            return 1
        if args.write:
            count = write_generated_outputs(root)
            print(f"Generated {count} adapter file(s).")
        failures = validate_generated_outputs(root)
    except (OSError, UnicodeError, ValueError) as exc:
        print(exc)
        return 1
    if failures:
        for failure in failures:
            print(failure)
        return 1
    print("Platform adapters: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
