#!/usr/bin/env python3
# Generated by scripts/generate_platform_adapters.py; do not edit.
"""Convert a human-supplied Confluence page export into a DRAFT runbook.

Mechanical assistance for the import flow in ../references/confluence-import.md — a HUMAN (or the
software-engineer agent) runs this on an exported page; scribe then edits the draft into a reviewable runbook.
The script never fetches anything: its input is a file the human already exported (view/export
HTML converts best; storage-format XHTML is handled best-effort, with its macro elements counted
as losses rather than mangled).

The draft retains source sections, links and image references, marks commands unverified, and
reports unsupported content and uncopied attachments. It never fetches linked resources or turns
an import into verification. Covered by scripts/test_confluence_import.py.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import quote, urlsplit

# Template slot order mirrors assets/runbook-template.md; headings must match it byte-for-byte so
# a converted draft diffs cleanly against a hand-copied template.
SLOTS = (
    "Purpose & scope",
    "Trigger",
    "Prerequisites",
    "Triage / first checks",
    "Procedure",
    "Verification",
    "Rollback / cleanup",
    "Escalation",
    "Communication",
)

# Source-heading keywords → template slot. Matched against the lowercased heading text; first hit
# wins in this order. Deliberately narrow: a wrong guess buries content in the wrong slot, while a
# miss lands it — visibly — in "Imported content (unmapped)". Err toward the miss.
SLOT_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Trigger", ("when to use", "trigger", "symptom", "alert")),
    ("Prerequisites", ("before you start", "prerequisite", "requirement", "access", "tooling", "tools")),
    ("Triage / first checks", ("triage", "first check", "diagnos", "impact")),
    ("Procedure", ("step", "procedure", "resolution", "remediat", "instruction", "process", "fix")),
    ("Verification", ("verif", "validat", "confirm")),
    ("Rollback / cleanup", ("rollback", "roll back", "revert", "undo", "backout", "back out", "cleanup")),
    ("Escalation", ("escalat", "on-call", "on call", "paging", "contact", "support")),
    ("Communication", ("communicat", "notif", "stakeholder", "comms")),
    ("Purpose & scope", ("purpose", "overview", "scope", "about", "goal", "summary")),
    ("References", ("reference", "related", "see also", "links")),
)

UNVERIFIED_MARK = "*Imported command — [unverified] until rehearsed on the target.*"
SERVICE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


class _Extractor(HTMLParser):
    """Flatten the export into (heading, blocks) sections.

    Blocks are ("text", str) paragraphs/list items or ("code", str) literal blocks. Content inside
    Confluence namespace elements (<ac:...>/<ri:...>) or unsupported media is suppressed and counted:
    a macro's innards are parameters, not prose, and half-copied parameters masquerading as
    instructions are worse than a reported loss. Unclosed suppressed tags can leave suppression
    active; the failure direction is suppressing too much into the loss count, never inventing content.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title = ""
        self.sections: list[tuple[str, list[tuple[str, str]]]] = [("", [])]
        self.macro_count = 0
        self.image_count = 0
        self.media_count = 0
        self.unusable_destinations = 0
        self._ac_depth = 0
        self._media: list[str] = []
        self._in_title = False
        self._heading: str | None = None
        self._pre: list[str] | None = None
        self._text: list[str] = []
        self._list_stack: list[str] = []
        self._link: tuple[int, str] | None = None

    def _destination(self, value: str | None) -> str:
        value = (value or "").strip()
        try:
            valid = bool(value) and not any(ord(c) < 32 for c in value)
            valid = valid and urlsplit(value).scheme.lower() in {"", "http", "https", "mailto"}
        except ValueError:
            valid = False
        if not valid:
            self.unusable_destinations += 1
            return ""
        return quote(value, safe="/:#?&=%@+;,-._~")

    @staticmethod
    def _reference(label: str, destination: str) -> str:
        label = " ".join(label.split())
        label = re.sub(r"([\\`*_\[\]{}()#+.!|<>~-])", r"\\\1", label)
        return f"[{label}](<{destination}>)" if destination else label

    def _finish_link(self) -> None:
        if self._link is not None:
            start, destination = self._link
            label = " ".join(self._text[start:]).strip() or destination
            self._text[start:] = [self._reference(label, destination)]
            self._link = None

    def _flush_text(self) -> None:
        self._finish_link()
        text = " ".join(part for part in self._text if part).strip()
        self._text = []
        if not text:
            return
        prefix = "- " if self._list_stack else ""
        self.sections[-1][1].append(("text", prefix + text))

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in {"iframe", "object", "embed", "video", "audio", "svg"} and not self._ac_depth:
            self.media_count += 1
            if tag != "embed":  # Void media has no descendants to suppress.
                self._media.append(tag)
            return
        if self._media:
            return
        if ":" in tag:  # ac:/ri: namespace — Confluence macro machinery, not content
            if self._ac_depth == 0:
                self.macro_count += 1
            self._ac_depth += 1
            return
        if self._ac_depth:
            return
        if tag == "a" and self._pre is None and self._heading is None and not self._in_title:
            self._finish_link()
            if "href" in dict(attrs):
                self._link = (len(self._text), self._destination(dict(attrs)["href"]))
        elif tag == "img":
            self.image_count += 1
            attributes = dict(attrs)
            self._text.append("Image: " + self._reference(
                attributes.get("alt") or "image", self._destination(attributes.get("src"))
            ))
        if tag == "title":
            self._in_title = True
        elif tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            self._flush_text()
            self._heading = ""
        elif tag == "pre":
            self._flush_text()
            self._pre = []
        elif tag in {"ul", "ol"}:
            self._flush_text()
            self._list_stack.append(tag)
        elif tag in {"p", "li", "tr", "br"}:
            if tag != "br" or self._link is None:
                self._flush_text()

    def handle_endtag(self, tag: str) -> None:
        if self._media:
            if tag == self._media[-1]:
                self._media.pop()
            return
        if ":" in tag:
            self._ac_depth = max(0, self._ac_depth - 1)
            return
        if self._ac_depth:
            return
        if tag == "a":
            self._finish_link()
        if tag == "title":
            self._in_title = False
        elif tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            heading = (self._heading or "").strip()
            self._heading = None
            if tag == "h1" and heading and not self.title:
                self.title = heading
            elif heading and heading != self.title:
                self.sections.append((heading, []))
        elif tag == "pre" and self._pre is not None:
            code = "".join(self._pre).strip("\n")
            self._pre = None
            if code.strip():
                self.sections[-1][1].append(("code", code))
        elif tag in {"ul", "ol"} and self._list_stack:
            self._flush_text()
            self._list_stack.pop()
        elif tag in {"p", "li", "tr"}:
            self._flush_text()

    def handle_data(self, data: str) -> None:
        if self._ac_depth or self._media:
            return
        if self._in_title:
            self.title += data.strip()
        elif self._heading is not None:
            self._heading += data
        elif self._pre is not None:
            self._pre.append(data)
        elif data.strip():
            self._text.append(re.sub(r"\s+", " ", data).strip())

    def close(self) -> None:
        self._flush_text()
        super().close()


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or "imported-runbook"


def service_id(value: str) -> str:
    """Accept only the stable slug shape required by runbook-frontmatter-v1."""
    if not SERVICE_ID_RE.fullmatch(value):
        raise argparse.ArgumentTypeError(
            "service-id must match ^[a-z0-9][a-z0-9-]*$"
        )
    return value


def owner(value: str) -> str:
    """Reject owner values that cannot satisfy the frontmatter schema."""
    if not value.strip():
        raise argparse.ArgumentTypeError(
            "owner must contain at least one non-whitespace character"
        )
    return value


def map_slot(heading: str) -> str | None:
    lowered = heading.lower()
    for slot, keywords in SLOT_KEYWORDS:
        if any(keyword in lowered for keyword in keywords):
            return slot
    return None


def render_blocks(blocks: list[tuple[str, str]]) -> list[str]:
    lines: list[str] = []
    for kind, value in blocks:
        if kind == "code":
            lines += ["```", value, "```", UNVERIFIED_MARK, ""]
        else:
            lines += [value, ""]
    return lines


def convert(source: Path, source_url: str | None, service_id: str, owner: str) -> tuple[str, str]:
    """Return (draft_markdown, stdout_report)."""
    parser = _Extractor()
    parser.feed(source.read_text(encoding="utf-8", errors="replace"))
    parser.close()

    title = parser.title or source.stem
    mapped: dict[str, list[str]] = {}
    unmapped: list[str] = []
    report: list[str] = [f"Converted: {source.name} — “{title}”"]
    for heading, blocks in parser.sections:
        if not blocks:
            continue
        slot = map_slot(heading) if heading else "Purpose & scope"
        body = render_blocks(blocks)
        if slot:
            note = f"*(from source section: “{heading}”)*" if heading else ""
            mapped.setdefault(slot, []).extend(([note, ""] if note else []) + body)
            report.append(f"  mapped   “{heading or '(intro)'}” -> {slot}")
        else:
            unmapped += [f"### {heading}", ""] + body
            report.append(f"  unmapped “{heading}” -> Imported content (unmapped)")

    today = datetime.date.today().isoformat()
    losses = [
        f"Confluence macros dropped (not convertible): {parser.macro_count}",
        f"Image attachments not copied: {parser.image_count} (references retained where usable)",
        f"Unsupported media dropped: {parser.media_count}",
        f"Unusable link or image destinations: {parser.unusable_destinations}",
    ]
    report.extend(f"  losses: {loss}" for loss in losses)

    lines = [
        "---",
        "schema_version: 1",
        f"runbook_id: {slugify(title)}",
        f"service_id: {json.dumps(service_id, ensure_ascii=False)}",
        "status: draft",
        "alert_names: []",
        f"owner: {json.dumps(owner, ensure_ascii=False)}",
        "severity: <P1|P2|P3|P4 / page | ticket>",
        "source_revision: <repository@short-commit or reviewed release identifier>",
        "last_reviewed: null",
        "last_verified: null",
        "verification_evidence: []",
        "version: 1",
        "---",
        "",
        f"# Runbook: {title}",
        "",
        "> **Imported draft.** Converted from a Confluence export; every command below is",
        "> `[unverified]` until rehearsed on the target, and every empty slot must be filled or",
        "> marked “n/a — why” before this leaves `draft`. See the runbook skill's Confluence-import",
        "> reference for the provenance rules this draft follows.",
        "",
    ]
    for slot in SLOTS:
        lines.append(f"## {slot}")
        lines.append("")
        content = mapped.get(slot)
        lines += content if content else ["<fill in — not present in the source page>", ""]
    lines += [
        "## Post-Incident",
        "",
        "- [ ] Append an Incident history row: version used, steps that held, steps that failed",
        "      or were missing, and the follow-up reference.",
        "- [ ] Create a learning disposition for every missing, contradicted, or newly useful step.",
        "",
        "## Incident history (living-runbook accretion)",
        "",
        "| Date (UTC) | Incident / drill ref | Version used | Steps that held | Steps that failed / were missing | Follow-up (disposition / PR or evidence reference) |",
        "|---|---|---|---|---|---|",
        "",
        "## Imported content (unmapped)",
        "",
    ]
    lines += unmapped if unmapped else ["(nothing — every source section mapped to a slot)", ""]
    lines += ["## References", ""]
    if "References" in mapped:
        lines += mapped["References"]
    lines += [
        "**Import provenance**",
        "",
        f"- Source file: `{source.name}`",
        f"- Source page title: “{title}”",
    ]
    if source_url:
        lines.append(f"- Source page URL: {json.dumps(source_url, ensure_ascii=False)}")
    lines += [f"- Converted: {today}"] + [f"- Conversion losses: {loss}" for loss in losses] + [""]
    return "\n".join(lines), "\n".join(report)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("source", type=Path, help="exported Confluence page (view/export HTML preferred)")
    parser.add_argument("-o", "--output", type=Path, required=True, help="draft runbook path to write")
    parser.add_argument("--source-url", default=None, help="original page URL for provenance")
    parser.add_argument("--service-id", required=True, type=service_id)
    parser.add_argument("--owner", default="<team/role>", type=owner)
    args = parser.parse_args(argv)

    if not args.source.is_file():
        print(f"error: cannot read {args.source}", file=sys.stderr)
        return 1
    draft, report = convert(args.source, args.source_url, args.service_id, args.owner)
    args.output.write_text(draft, encoding="utf-8")
    print(report)
    print(f"Draft written: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
